FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

COPY .env .env

ENV PYTHONPATH=/

CMD ["python", "generate_device_interactions/main.py"]